import type { WitboostConfig } from "../config/schema.js";

/**
 * Where generated files land:
 * - "workspace" (default): inside the target repo, committed to git.
 * - "user": the harness's own home-directory config, e.g. ~/.claude, shared
 *   across every repo on the machine instead of copied into each one.
 * - "shared": a custom directory (see --shared-dir) covering a narrower set
 *   of repos than the whole home directory — typically the common parent
 *   folder of several sibling adapter repos. Claude Code and Gemini CLI
 *   natively load their root instructions file from every directory above
 *   the working directory, so this works with zero extra config for them;
 *   other harnesses need additional manual setup (see README).
 */
export type HarnessScope = "workspace" | "user" | "shared";

/** Overrides for specific harness generators */
export interface HarnessOverrides {
  copilot?: { command?: string; argumentHint?: string };
  claude?: { subcommand?: string };
  codex?: { section?: string };
  gemini?: Record<string, never>;
}

/** Skill definition parsed from SKILL.md YAML frontmatter */
export interface SkillDefinition {
  name: string;
  description: string;
  /** Absolute path to the canonical skill directory (for copying into native locations) */
  dirPath: string;
  /** Full SKILL.md content (frontmatter + body) */
  content: string;
}

/** Canonical agent definition parsed from YAML+Markdown */
export interface AgentDefinition {
  name: string;
  displayName: string;
  description: string;
  tools: string[];
  skills: string[];
  resolvedSkills: SkillDefinition[];
  category?: string;
  instructions: string;
  harness?: HarnessOverrides;
  /** Agent names this agent should suggest transitioning to once its phase is done */
  handoffs?: string[];
  /** Only generate this agent in the workflow host repo, never in a target adapter repo */
  hostOnly?: boolean;
}

/** A file generated by a harness generator */
export interface GeneratedFile {
  path: string;
  content: string;
  overwrite: boolean;
  /**
   * "overwrite" (default) replaces the file wholesale — safe for files this
   * toolkit fully owns (per-agent files, workspace-scope files). "managed-block"
   * upserts a marked region inside a file that may also hold the user's own
   * unrelated content (e.g. a shared ~/.claude/CLAUDE.md, or a shared-dir
   * CLAUDE.md covering several sibling repos) — required whenever scope is
   * "user" or "shared" and the harness only supports a single root file.
   */
  mergeStrategy?: "overwrite" | "managed-block";
}

/** Interface for pluggable harness generators */
export interface HarnessGenerator {
  harnessName: string;
  generate(
    agents: AgentDefinition[],
    config: WitboostConfig,
    repoRoot: string,
    scope: HarnessScope,
  ): GeneratedFile[];
}
