import type { WitboostConfig } from "../config/schema.js";

/** Public workspace output or internal generation for this toolkit repository. */
export type OutputMode = "folder" | "self-host";

/** Overrides for specific harness generators */
export interface HarnessOverrides {
  copilot?: { command?: string; argumentHint?: string };
  claude?: { subcommand?: string };
  codex?: { section?: string };
  gemini?: Record<string, never>;
}

/** Skill definition parsed from SKILL.md YAML frontmatter */
export interface SkillDefinition {
  name: string;
  description: string;
  /** Absolute path to the canonical skill directory (for copying into native locations) */
  dirPath: string;
  /** Full SKILL.md content (frontmatter + body) */
  content: string;
}

/** Canonical agent definition parsed from YAML+Markdown */
export interface AgentDefinition {
  name: string;
  displayName: string;
  description: string;
  tools: string[];
  skills: string[];
  resolvedSkills: SkillDefinition[];
  category?: string;
  instructions: string;
  harness?: HarnessOverrides;
  /** Agent names this agent should suggest transitioning to once its phase is done */
  handoffs?: string[];
}

/** A file generated by a harness generator */
export interface GeneratedFile {
  path: string;
  content: string;
  overwrite: boolean;
  /**
   * "overwrite" (default) replaces the file wholesale — safe for files this
   * toolkit fully owns (per-agent files and self-hosted files). "managed-block"
   * upserts a marked region inside a file that may also hold the user's own
   * unrelated content in the configured workspace folder.
   */
  mergeStrategy?: "overwrite" | "managed-block";
}

/** Interface for pluggable harness generators */
export interface HarnessGenerator {
  harnessName: string;
  generate(
    agents: AgentDefinition[],
    config: WitboostConfig,
    repoRoot: string,
    mode: OutputMode,
  ): GeneratedFile[];
}
