# templates use "readonly" in a parameters.yaml file to store constant values. most of the times this is not even needed. it is needed when the user explicitly asks to store some readonly constant values in templates.
# NEVER hardcode sample data here
# reserved fields, DO NOT NAME your own parameters with these names:
# __system__ links this component to its parent Data Product.
# __version__ is derived from the component identifier.
# if you do NOT need readonly values, AVOID creating a parameters.yaml file at all, and Witboost will auto-generate it for you. 
readonly: {}
