apiVersion: witboost.com/v2
kind: EditTemplate
metadata:
  name: edit-data-product-template.0 # this is the unique identifier for the edit template in witboost
  title: Edit Data Product # this is the human-readable title for the edit template visible in the Witboost UI
  description: Edit a Data Product system created with the Data Product Template # this describes the purpose of the edit template in the Witboost UI. Not visible by the user. Does not matter to have a detailed description here.
  mesh:
    icon: https://cdn-icons-png.flaticon.com/256/2666/2666501.png
  tags:
    - data-product
    - edit

spec:
  owner: witboost
  useCaseTemplateId:
    - urn:dmb:utm:data-product-template:0.0.0 # this must match the URN of the creation template that this Edit Template is associated with

  parameters:
    - title: Edit Data Product Information # title of the step
      required: # mandatory fields. if users do not provide these, the form will block the user from proceeding
        - description
        - projectOwner
        - developmentGroup
      properties:
        name: # always required by every Witboost project
          title: Name
          type: string
          description: Data Product name # "Data Product" may vary according to the specific context or terminology used in your organization. Same for all other fields in this example template
          ui:disabled: true # name is not editable in edit mode, so we disable it. We still show it to the user for reference.
        domain: # always required by every Witboost project 
          title: Domain
          type: string
          description: Domain this Data Product belongs to 
          ui:field: EntityPicker
          ui:disabled: true # domain is not editable in edit mode, so we disable it. We still show it to the user for reference.
          ui:options:
            allowArbitraryValues: false
            allowedKinds:
              - Domain

        domainName: # no need to disable as it is hidden so not visible by the user in the UI
          type: string
          ui:field: EntitySelectionPicker
          ui:fieldName: domain
          ui:property: spec.mesh.name
          ui:options:
            allowArbitraryValues: false
          ui:widget: hidden # the hidden field is a pattern used to retrieve the domain name associated with the selected domain entity above. it's hidden because it's a data field not meant for direct user input.

        identifier: # always required by every Witboost project
          title: Identifier
          type: string
          description: Autogenerated unique identifier.
          ui:field: IdentifierPicker
          ui:disabled: true 
          ui:options:
            allowArbitraryValues: false
        
        description:
          title: Description
          type: string
          description: Description of purpose and scope of this Data Product

        projectOwner: # always required by every Witboost project
          title: Data Product Owner # may vary according to the specific context or terminology used in your organization.
          type: string
          description: Responsible person for the Data Product from a business perspective
          ui:field: EntityPicker
          ui:options:
            allowArbitraryValues: false
            allowedKinds:
              - User
        developmentGroup: # always required by every Witboost project
          title: Development Group # may vary according to the specific context or terminology used in your organization.
          type: string
          description: Group of developers with access to the Data Product repositories.
          ui:field: EntityPicker
          ui:options:
            allowArbitraryValues: false
            allowedKinds:
              - Group
        email:
          title: Support Contact Email
          type: string
          format: email
          description: Point of contact for support requests.

        tags:
          title: Tags
          type: array
          description: Tags for classification and search.
          default: []
          items:
            type: string

    # You can always add additional update steps here as needed. 
    # Usually, the edit template has the same steps of the creation template. sometimes the edit template presents more fields compared to the creation template.
    # The more steps you add, the more complex your project setup can become and the user may lose track of the overall flow. For edit template, having more steps and fields is fine, since users can update different aspects of the project as needed and at different times.
    - title: Update step
      properties:
        exampleProperty:
          title: Example Property
          type: string
          description: An example property for the additional step.


# the edit template has no steps section nor outputs section